# Generated by Django 4.0.5 on 2022-07-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProject',
            new_name='Myapp',
        ),
    ]
